field: 383f3683-9ae9-447a-b478-59400a6b6298 # Quick Links
fieldLayouts:
  9bc709d5-7262-4e05-9b91-e5648f447b6b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 94df1a09-8faf-4017-b9a3-16bc3639889b # Display Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e4419bd-e205-4dad-bf88-1455ffd0a2bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2e01b95d-9e2c-4e43-96fd-db0f572cb1a9 # Off-Site URL
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a759cc35-0806-4b84-b86f-079a160b327f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c797a75-4d38-4c45-ab92-2c3e8496b556
        userCondition: null
fields:
  2e01b95d-9e2c-4e43-96fd-db0f572cb1a9: # Off-Site URL
    columnSuffix: izqumoew
    contentColumnType: string(255)
    fieldGroup: null
    handle: offSiteUrl
    instructions: 'Always opens in a new tab.'
    name: 'Off-Site URL'
    searchable: true
    settings:
      maxLength: 255
      types:
        - url
        - tel
        - email
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  94df1a09-8faf-4017-b9a3-16bc3639889b: # Display Text
    columnSuffix: lnmrjisy
    contentColumnType: text
    fieldGroup: null
    handle: displayText
    instructions: null
    name: 'Display Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: externalLink
name: 'External Link'
sortOrder: 1
