fieldLayouts:
  e9edf03f-d914-4a29-864b-ee88291bacd8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 901a7e7b-2675-4f07-8873-e134aecd5113
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8b88dd11-2096-4b80-aeef-bddc0ebc68dd # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df31dc7b-efae-4ab0-bf13-ee3d2ceea980
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 383f3683-9ae9-447a-b478-59400a6b6298 # Quick Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fccd64cc-b5ff-40ef-91ae-5dd0eb41fef6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5ab8d789-0931-45eb-b414-2f726a73398f
        userCondition: null
handle: links
hasTitleField: false
name: Links
section: 675db4a7-3326-4288-bdf2-23eccd2af4ae # Links
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
