baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Southerners Organizing To Neutralize Fundamentalism'
primary: true
siteGroup: fef3d636-b821-4114-ae4c-da7cd50586f6 # craft4-ddev-test
sortOrder: 1
