columnSuffix: null
contentColumnType: string
fieldGroup: 9b026b15-c4ab-49fd-8fba-f6931276e42c # Links
handle: quickLinks
instructions: null
name: 'Quick Links'
searchable: true
settings:
  contentTable: '{{%matrixcontent_quicklinks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
