defaultPlacement: end
enableVersioning: true
handle: homepage
name: homepage
propagationMethod: all
siteSettings:
  a438467d-9ba0-490f-8668-0ebdbad4d63f: # Southerners Organizing To Neutralize Fundamentalism - $DDEV_SITENAME
    enabledByDefault: true
    hasUrls: true
    template: homepage/_homepage.twig
    uriFormat: __home__
type: single
