defaultPlacement: end
enableVersioning: true
handle: links
name: Links
propagationMethod: all
siteSettings:
  a438467d-9ba0-490f-8668-0ebdbad4d63f: # craft4-ddev-test
    enabledByDefault: true
    hasUrls: true
    template: links/_entry
    uriFormat: links
type: single
